name: CI

on:
  push:
    branches: [ "main" ] # Trigger the workflow on pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu image as the runner

    steps:
    - uses: actions/checkout@v3 # Check out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # Specify the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest 

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results 
